import { describe, expect, it, beforeEach, afterEach, vi } from 'vitest';
import { render, screen } from '@testing-library/react';
import { OperatorApp } from '../src/renderer/App.jsx';

const now = '2026-04-07T05:00:00.000Z';

function createSnapshot() {
  return {
    schemaVersion: 2,
    system: {
      startedAt: now,
      lastTickAt: now,
      lastActivityAt: now,
      lastHeartbeatAt: null,
      activeTaskId: null,
    },
    settings: {
      locale: 'en',
      activeWorkspaceId: 'workspace-default',
      workspacePath: '',
      autoLoop: true,
      paused: false,
      autoLoopIntervalMs: 60_000,
      providerMode: 'scripted',
      providerCommand: '',
      providerTimeoutMs: 120_000,
      runnerMode: 'simulated',
      runnerCommand: '',
      runnerTimeoutMs: 120_000,
      permissions: {
        read: true,
        write: true,
        test: true,
        pr: false,
        merge: false,
        deploy: false,
        selfEdit: false,
      },
      requireHighRiskApproval: true,
      maxRetries: 2,
    },
    workspaces: [
      {
        id: 'workspace-default',
        name: 'Workspace 1',
        path: '',
        description: 'Starter workspace with no path configured yet.',
        providerMode: 'scripted',
        providerCommand: '',
        providerTimeoutMs: 120_000,
        runnerMode: 'simulated',
        runnerCommand: '',
        runnerTimeoutMs: 120_000,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'workspace-docs',
        name: 'Docs Workspace',
        path: '/tmp/docs',
        description: 'Documentation and content checks.',
        providerMode: 'command',
        providerCommand: 'node "./scripts/codex-provider.mjs"',
        providerTimeoutMs: 120_000,
        runnerMode: 'shell',
        runnerCommand: 'pnpm test docs',
        runnerTimeoutMs: 120_000,
        createdAt: now,
        updatedAt: now,
      },
    ],
    taskTemplates: [
      {
        id: 'template-default-workspace',
        workspaceId: 'workspace-default',
        workspacePath: '',
        title: 'Bootstrap the workspace',
        objective: 'Inspect the selected workspace and propose one safe improvement.',
        scope: 'workspace',
        kind: 'maintenance',
        priority: 5,
        providerMode: 'scripted',
        providerCommand: '',
        providerTimeoutMs: 120_000,
        runnerMode: 'simulated',
        runnerCommand: '',
        runnerTimeoutMs: 120_000,
        description: 'Starter task template for the default workspace.',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'template-docs-bootstrap',
        workspaceId: 'workspace-docs',
        workspacePath: '/tmp/docs',
        title: 'Docs bootstrap',
        objective: 'Use the Codex wrapper to inspect the docs workspace and propose one safe improvement.',
        scope: 'workspace',
        kind: 'maintenance',
        priority: 4,
        providerMode: 'command',
        providerCommand: 'node "./scripts/codex-provider.mjs"',
        providerTimeoutMs: 120_000,
        runnerMode: 'shell',
        runnerCommand: 'pnpm test docs',
        runnerTimeoutMs: 120_000,
        description: 'Seeded task template for the docs workspace.',
        createdAt: now,
        updatedAt: now,
      },
    ],
    tasks: [
      {
        id: 'task-1',
        title: 'Inspect repo',
        objective: 'Review the workspace and summarize one next step.',
        scope: 'workspace',
        workspacePath: '',
        providerMode: 'scripted',
        providerCommand: '',
        providerTimeoutMs: 120_000,
        runnerMode: 'simulated',
        runnerCommand: '',
        runnerTimeoutMs: 120_000,
        priority: 3,
        kind: 'analysis',
        status: 'completed',
        resumeFromStepIndex: 4,
        retryCount: 0,
        createdAt: now,
        updatedAt: now,
        parentTaskId: null,
        sourceTaskId: null,
        autoGenerated: false,
        pendingApprovalId: null,
        blockedReason: null,
        review: {
          approved: true,
          needsFollowUp: false,
          notes: 'Completed successfully.',
          followUpTitle: '',
          followUpObjective: '',
        },
        plan: {
          summary: 'Inspect the workspace and report back.',
          workerPrompt: 'Worker prompt',
          reviewPrompt: 'Reviewer prompt',
        },
        steps: [
          {
            id: 'step-1',
            title: 'Review context',
            role: 'worker',
            kind: 'analysis',
            permission: 'read',
            command: '',
            note: 'Inspect the workspace.',
          },
        ],
        stepResults: [],
        approvedSteps: [],
        logs: [],
      },
    ],
    approvals: [],
    logs: [],
    memory: [],
  };
}

describe('renderer app', () => {
  const operator = {
    getSnapshot: vi.fn(),
    subscribe: vi.fn(),
    createTask: vi.fn(),
    updateSettings: vi.fn(),
    setLocale: vi.fn(),
    setWorkspacePath: vi.fn(),
    createWorkspace: vi.fn(),
    updateWorkspace: vi.fn(),
    setActiveWorkspace: vi.fn(),
    updateWorkspaceTemplate: vi.fn(),
    pause: vi.fn(),
    resume: vi.fn(),
    toggleAutoLoop: vi.fn(),
    seedDemoTasks: vi.fn(),
    seedWorkspaceTask: vi.fn(),
    approveTask: vi.fn(),
    rejectTask: vi.fn(),
    runOnce: vi.fn(),
    selectWorkspace: vi.fn(),
  };

  beforeEach(() => {
    operator.getSnapshot.mockResolvedValue(createSnapshot());
    operator.subscribe.mockReturnValue(() => {});
  });

  afterEach(() => {
    vi.clearAllMocks();
  });

  it('renders the bilingual control surface with task data', async () => {
    render(<OperatorApp api={operator} />);
    await screen.findByRole('heading', { name: 'Task Intake' });
    expect(screen.getByText('Workspaces')).toBeInTheDocument();
    expect(screen.getByRole('button', { name: 'Seed workspace template' })).toBeInTheDocument();
    expect(screen.getByText('Workspace 1', { selector: '.workspace-picker-head strong' })).toBeInTheDocument();
    expect(screen.getByText('Docs Workspace')).toBeInTheDocument();
    expect(screen.getByText('Inspect repo', { selector: 'strong' })).toBeInTheDocument();
    expect(screen.getByText('Task Template')).toBeInTheDocument();
    expect(screen.getByRole('heading', { name: 'Approval Queue' })).toBeInTheDocument();
  });
});
