import { describe, expect, it, beforeEach, afterEach, vi } from 'vitest';
import { cleanup, render, screen } from '@testing-library/react';
import { OperatorApp } from '../src/renderer/App.jsx';

const now = '2026-04-07T05:00:00.000Z';

function createSnapshot() {
  return {
    schemaVersion: 2,
    system: {
      startedAt: now,
      lastTickAt: now,
      lastActivityAt: now,
      lastHeartbeatAt: null,
      activeTaskId: null,
    },
    settings: {
      locale: 'en',
      activeWorkspaceId: 'workspace-default',
      workspacePath: '',
      autoLoop: true,
      paused: false,
      autoLoopIntervalMs: 60_000,
      providerMode: 'scripted',
      providerCommand: '',
      providerTimeoutMs: 120_000,
      runnerMode: 'simulated',
      runnerCommand: '',
      runnerTimeoutMs: 120_000,
      permissions: {
        read: true,
        write: true,
        test: true,
        pr: false,
        merge: false,
        deploy: false,
        selfEdit: false,
      },
      requireHighRiskApproval: true,
      maxRetries: 2,
    },
    workspaces: [
      {
        id: 'workspace-default',
        name: 'Workspace 1',
        path: '',
        description: 'Starter workspace with no path configured yet.',
        leadAgentId: 'astra',
        providerMode: 'scripted',
        providerCommand: '',
        providerTimeoutMs: 120_000,
        runnerMode: 'simulated',
        runnerCommand: '',
        runnerTimeoutMs: 120_000,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'workspace-docs',
        name: 'Docs Workspace',
        path: '/tmp/docs',
        description: 'Documentation and content checks.',
        leadAgentId: 'astra',
        providerMode: 'command',
        providerCommand: 'node "./scripts/codex-provider.mjs"',
        providerTimeoutMs: 120_000,
        runnerMode: 'shell',
        runnerCommand: 'pnpm test docs',
        runnerTimeoutMs: 120_000,
        createdAt: now,
        updatedAt: now,
      },
    ],
    taskTemplates: [
      {
        id: 'template-default-workspace',
        workspaceId: 'workspace-default',
        workspacePath: '',
        title: 'Bootstrap the workspace',
        objective: 'Inspect the selected workspace and propose one safe improvement.',
        scope: 'workspace',
        kind: 'maintenance',
        priority: 5,
        ownerAgentId: 'astra',
        departmentId: 'command',
        providerMode: 'scripted',
        providerCommand: '',
        providerTimeoutMs: 120_000,
        runnerMode: 'simulated',
        runnerCommand: '',
        runnerTimeoutMs: 120_000,
        description: 'Starter task template for the default workspace.',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'template-docs-bootstrap',
        workspaceId: 'workspace-docs',
        workspacePath: '/tmp/docs',
        title: 'Docs bootstrap',
        objective: 'Use the Codex wrapper to inspect the docs workspace and propose one safe improvement.',
        scope: 'workspace',
        kind: 'maintenance',
        priority: 4,
        providerMode: 'command',
        providerCommand: 'node "./scripts/codex-provider.mjs"',
        providerTimeoutMs: 120_000,
        runnerMode: 'shell',
        runnerCommand: 'pnpm test docs',
        runnerTimeoutMs: 120_000,
        description: 'Seeded task template for the docs workspace.',
        createdAt: now,
        updatedAt: now,
      },
    ],
    tasks: [
      {
        id: 'task-1',
        title: 'Inspect repo',
        objective: 'Review the workspace and summarize one next step.',
        scope: 'workspace',
        workspacePath: '',
        providerMode: 'scripted',
        providerCommand: '',
        providerTimeoutMs: 120_000,
        runnerMode: 'simulated',
        runnerCommand: '',
        runnerTimeoutMs: 120_000,
        priority: 3,
        kind: 'analysis',
        status: 'completed',
        resumeFromStepIndex: 4,
        retryCount: 0,
        createdAt: now,
        updatedAt: now,
        parentTaskId: null,
        sourceTaskId: null,
        autoGenerated: false,
        pendingApprovalId: null,
        blockedReason: null,
        review: {
          approved: true,
          needsFollowUp: false,
          notes: 'Completed successfully.',
          followUpTitle: '',
          followUpObjective: '',
        },
        plan: {
          summary: 'Inspect the workspace and report back.',
          workerPrompt: 'Worker prompt',
        reviewPrompt: 'Reviewer prompt',
      },
      steps: [
          {
            id: 'step-1',
            title: 'Review context',
            role: 'worker',
            kind: 'analysis',
            permission: 'read',
            command: '',
            note: 'Inspect the workspace.',
          },
        ],
        stepResults: [],
        approvedSteps: [],
        logs: [],
      },
    ],
    approvals: [],
    logs: [],
    memory: [],
    agents: [
      {
        id: 'astra',
        name: 'Astra',
        title: 'Lead Operator',
        departmentId: 'command',
        specialty: 'Owns the big goal and keeps every team aligned.',
        defaultFocus: 'Turn the workspace brief into a single mission.',
        accent: 'cyan',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'mira',
        name: 'Mira',
        title: 'Planning Director',
        departmentId: 'planning',
        specialty: 'Breaks a goal into clear subgoals and checkpoints.',
        defaultFocus: 'Translate the brief into a workable plan.',
        accent: 'gold',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'forge',
        name: 'Forge',
        title: 'Production Lead',
        departmentId: 'production',
        specialty: 'Turns the mission into shipped work.',
        defaultFocus: 'Keep the build lane moving.',
        accent: 'green',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'quill',
        name: 'Quill',
        title: 'Acceptance Lead',
        departmentId: 'acceptance',
        specialty: 'Verifies results and signs off releases.',
        defaultFocus: 'Check the result against acceptance criteria.',
        accent: 'amber',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'pulse',
        name: 'Pulse',
        title: 'Operations Manager',
        departmentId: 'operations',
        specialty: 'Keeps the system healthy, recovers failures, and watches retries.',
        defaultFocus: 'Protect the loop from stalls and regressions.',
        accent: 'violet',
        createdAt: now,
        updatedAt: now,
      },
    ],
    departments: [
      {
        id: 'command',
        name: 'Command',
        description: 'Keeps the company goal aligned and visible.',
        accent: 'cyan',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'planning',
        name: 'Planning',
        description: 'Turns a goal into a mission plan and checkpoints.',
        accent: 'gold',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'production',
        name: 'Production',
        description: 'Builds the work order and keeps momentum moving.',
        accent: 'green',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'acceptance',
        name: 'Acceptance',
        description: 'Checks quality and decides whether the mission is ready.',
        accent: 'amber',
        createdAt: now,
        updatedAt: now,
      },
      {
        id: 'operations',
        name: 'Operations',
        description: 'Protects the loop, handles retries, and watches health.',
        accent: 'violet',
        createdAt: now,
        updatedAt: now,
      },
    ],
  };
}

describe('renderer app', () => {
  const operator = {
    getSnapshot: vi.fn(),
    subscribe: vi.fn(),
    createTask: vi.fn(),
    updateSettings: vi.fn(),
    setLocale: vi.fn(),
    setWorkspacePath: vi.fn(),
    createWorkspace: vi.fn(),
    updateWorkspace: vi.fn(),
    setActiveWorkspace: vi.fn(),
    updateWorkspaceTemplate: vi.fn(),
    pause: vi.fn(),
    resume: vi.fn(),
    toggleAutoLoop: vi.fn(),
    seedDemoTasks: vi.fn(),
    seedWorkspaceTask: vi.fn(),
    approveTask: vi.fn(),
    rejectTask: vi.fn(),
    runOnce: vi.fn(),
    selectWorkspace: vi.fn(),
  };

  beforeEach(() => {
    operator.getSnapshot.mockResolvedValue(createSnapshot());
    operator.subscribe.mockReturnValue(() => {});
  });

  afterEach(() => {
    cleanup();
    vi.clearAllMocks();
  });

  it('renders the bilingual control surface with task data', async () => {
    render(<OperatorApp api={operator} />);
    await screen.findByRole('heading', { name: 'Mission Pipeline' });
    expect(screen.getByRole('heading', { name: 'Staff Roster' })).toBeInTheDocument();
    expect(screen.getByRole('heading', { name: 'Completed Missions' })).toBeInTheDocument();
    expect(screen.getByRole('heading', { name: 'Review Desk' })).toBeInTheDocument();
    expect(screen.getByText('Astra', { selector: '.agent-card .agent-name' })).toBeInTheDocument();
    expect(screen.getByText('Mira', { selector: '.agent-card .agent-name' })).toBeInTheDocument();
    expect(screen.getAllByText('Rank 5', { selector: '.rank-chip' }).length).toBeGreaterThanOrEqual(1);
    expect(screen.getByText('Inspect repo', { selector: '.pipeline-lane .mission-card .mission-head-copy strong' })).toBeInTheDocument();
    expect(screen.getByText('Current goal', { selector: '.hero-goal > span' })).toBeInTheDocument();
    expect(screen.getByRole('button', { name: 'Plan' })).toBeInTheDocument();
    expect(screen.getByRole('button', { name: 'Archive' })).toBeInTheDocument();
    expect(screen.queryByText('Worker prompt')).not.toBeInTheDocument();
    expect(screen.getAllByRole('button', { name: 'Open management' }).length).toBeGreaterThanOrEqual(1);
  });
});
