import { describe, expect, it } from 'vitest';
import { buildCompanyBoard } from '../src/renderer/companyBoard.js';

const now = '2026-04-07T05:00:00.000Z';

function createSnapshot() {
  return {
    settings: {
      activeWorkspaceId: 'workspace-default',
      workspacePath: '',
    },
    workspaces: [
      {
        id: 'workspace-default',
        name: 'Workspace 1',
        path: '',
        leadAgentId: 'astra',
      },
    ],
    taskTemplates: [
      {
        id: 'template-default-workspace',
        workspaceId: 'workspace-default',
        workspacePath: '',
        title: 'Bootstrap the workspace',
        objective: 'Inspect the selected workspace and propose one safe improvement.',
        scope: 'workspace',
        kind: 'maintenance',
        priority: 5,
        ownerAgentId: 'astra',
        departmentId: 'command',
      },
    ],
    agents: [
      { id: 'astra', name: 'Astra', title: 'Lead Operator', departmentId: 'command', specialty: 'Owns the goal.', defaultFocus: 'Set the mission.', accent: 'cyan', createdAt: now, updatedAt: now },
      { id: 'mira', name: 'Mira', title: 'Planning Director', departmentId: 'planning', specialty: 'Plans the mission.', defaultFocus: 'Shape the brief.', accent: 'gold', createdAt: now, updatedAt: now },
      { id: 'forge', name: 'Forge', title: 'Production Lead', departmentId: 'production', specialty: 'Executes the mission.', defaultFocus: 'Ship the work.', accent: 'green', createdAt: now, updatedAt: now },
      { id: 'quill', name: 'Quill', title: 'Acceptance Lead', departmentId: 'acceptance', specialty: 'Reviews the mission.', defaultFocus: 'Approve the result.', accent: 'amber', createdAt: now, updatedAt: now },
      { id: 'pulse', name: 'Pulse', title: 'Operations Manager', departmentId: 'operations', specialty: 'Watches stability.', defaultFocus: 'Protect the loop.', accent: 'violet', createdAt: now, updatedAt: now },
    ],
    departments: [
      { id: 'command', name: 'Command', description: 'Company goal and alignment.', accent: 'cyan', createdAt: now, updatedAt: now },
      { id: 'planning', name: 'Planning', description: 'Plan and checkpoints.', accent: 'gold', createdAt: now, updatedAt: now },
      { id: 'production', name: 'Production', description: 'Build and ship.', accent: 'green', createdAt: now, updatedAt: now },
      { id: 'acceptance', name: 'Acceptance', description: 'Verify and sign off.', accent: 'amber', createdAt: now, updatedAt: now },
      { id: 'operations', name: 'Operations', description: 'Health and retries.', accent: 'violet', createdAt: now, updatedAt: now },
    ],
    tasks: [
      {
        id: 'task-active',
        title: 'Inspect repo',
        objective: 'Review the workspace and summarize one next step.',
        scope: 'workspace',
        workspacePath: '',
        ownerAgentId: 'mira',
        departmentId: 'planning',
        providerMode: 'scripted',
        providerCommand: '',
        providerTimeoutMs: 120_000,
        runnerMode: 'simulated',
        runnerCommand: '',
        runnerTimeoutMs: 120_000,
        priority: 3,
        kind: 'analysis',
        status: 'executing',
        resumeFromStepIndex: 1,
        retryCount: 0,
        createdAt: now,
        updatedAt: now,
        parentTaskId: null,
        sourceTaskId: null,
        autoGenerated: false,
        pendingApprovalId: null,
        blockedReason: null,
        review: null,
        plan: {
          summary: 'Inspect the workspace and report back.',
          workerPrompt: 'Worker prompt',
          reviewPrompt: 'Reviewer prompt',
        },
        steps: [
          { id: 'step-1', title: 'Review context', role: 'worker', kind: 'analysis', permission: 'read', command: '', note: 'Inspect the workspace.' },
          { id: 'step-2', title: 'Make change', role: 'worker', kind: 'execute', permission: 'write', command: '', note: 'Implement a small improvement.' },
          { id: 'step-3', title: 'Run verification', role: 'worker', kind: 'test', permission: 'test', command: '', note: 'Run the smallest meaningful validation.' },
          { id: 'step-4', title: 'Reviewer pass', role: 'reviewer', kind: 'review', permission: 'read', command: '', note: 'Check whether the result satisfies the objective.' },
        ],
        stepResults: [
          { id: 'result-1', stepId: 'step-1', title: 'Review context', role: 'worker', permission: 'read', status: 'succeeded', command: '', exitCode: 0, stdout: 'Scan complete', stderr: '', startedAt: now, finishedAt: now, message: '' },
        ],
        approvedSteps: [],
        logs: [],
      },
      {
        id: 'task-done',
        title: 'Stabilize task pipeline',
        objective: 'Reduce manual approvals in low-risk workspace work.',
        scope: 'workspace',
        workspacePath: '',
        ownerAgentId: 'quill',
        departmentId: 'acceptance',
        providerMode: 'scripted',
        providerCommand: '',
        providerTimeoutMs: 120_000,
        runnerMode: 'simulated',
        runnerCommand: '',
        runnerTimeoutMs: 120_000,
        priority: 2,
        kind: 'maintenance',
        status: 'completed',
        resumeFromStepIndex: 4,
        retryCount: 0,
        createdAt: now,
        updatedAt: now,
        parentTaskId: null,
        sourceTaskId: null,
        autoGenerated: false,
        pendingApprovalId: null,
        blockedReason: null,
        review: {
          approved: true,
          needsFollowUp: false,
          notes: 'Completed successfully.',
          followUpTitle: '',
          followUpObjective: '',
        },
        plan: {
          summary: 'Apply a policy-safe change and then review it.',
          workerPrompt: 'Worker prompt',
          reviewPrompt: 'Reviewer prompt',
        },
        steps: [
          { id: 'step-5', title: 'Review policy', role: 'worker', kind: 'analysis', permission: 'read', command: '', note: 'Inspect current approval rules.' },
          { id: 'step-6', title: 'Implement policy change', role: 'worker', kind: 'execute', permission: 'write', command: '', note: 'Apply the requested improvement.' },
        ],
        stepResults: [
          { id: 'result-1', stepId: 'step-5', title: 'Review policy', role: 'worker', permission: 'read', status: 'succeeded', command: '', exitCode: 0, stdout: 'Policy reviewed', stderr: '', startedAt: now, finishedAt: now, message: '' },
          { id: 'result-2', stepId: 'step-6', title: 'Implement policy change', role: 'worker', permission: 'write', status: 'succeeded', command: '', exitCode: 0, stdout: 'Change applied', stderr: '', startedAt: now, finishedAt: now, message: '' },
        ],
        approvedSteps: [],
        logs: [],
      },
      {
        id: 'task-blocked',
        title: 'Refine operator policies',
        objective: 'Update the orchestration core with a small change.',
        scope: 'orchestrator',
        workspacePath: '',
        ownerAgentId: 'astra',
        departmentId: 'command',
        providerMode: 'command',
        providerCommand: 'node ./scripts/codex-provider.mjs',
        providerTimeoutMs: 120_000,
        runnerMode: 'shell',
        runnerCommand: 'pnpm test docs',
        runnerTimeoutMs: 120_000,
        priority: 5,
        kind: 'custom',
        status: 'waiting-approval',
        resumeFromStepIndex: 1,
        retryCount: 0,
        createdAt: now,
        updatedAt: now,
        parentTaskId: null,
        sourceTaskId: null,
        autoGenerated: false,
        pendingApprovalId: 'approval-1',
        blockedReason: 'Awaiting high-risk approval',
        review: null,
        plan: {
          summary: 'Apply a policy-safe change and then review it.',
          workerPrompt: 'Worker prompt',
          reviewPrompt: 'Reviewer prompt',
        },
        steps: [
          { id: 'step-7', title: 'Review policy', role: 'worker', kind: 'analysis', permission: 'read', command: '', note: 'Inspect current approval rules.' },
          { id: 'step-8', title: 'Implement policy change', role: 'worker', kind: 'execute', permission: 'selfEdit', command: '', note: 'Apply the requested improvement.' },
        ],
        stepResults: [],
        approvedSteps: [],
        logs: [],
      },
    ],
    approvals: [
      {
        id: 'approval-1',
        taskId: 'task-blocked',
        stepId: 'step-8',
        stepIndex: 1,
        action: 'selfEdit',
        reason: 'High-risk self-edit requires approval.',
        decision: 'pending',
        requestedAt: now,
        resolvedAt: null,
      },
    ],
    logs: [],
    memory: [],
  };
}

describe('company board model', () => {
  it('builds a readable command-center view from tasks and staff metadata', () => {
    const board = buildCompanyBoard(createSnapshot());

    expect(board.leadAgent.id).toBe('astra');
    expect(board.metrics.pendingApprovals).toBe(1);
    expect(board.activeMission.id).toBe('task-blocked');
    expect(board.activeMission.owner.name).toBe('Astra');
    expect(board.activeMission.owner.avatar).toBe('AS');
    expect(board.activeMission.owner.rank).toBe(5);
    expect(board.activeMission.progress).toBeGreaterThan(0);
    expect(board.agents).toHaveLength(5);
    expect(board.departments).toHaveLength(5);
    expect(board.pipelineStages).toHaveLength(4);
    expect(board.pipelineStages.map((stage) => stage.id)).toEqual(['plan', 'execute', 'review', 'archive']);
    expect(board.pipelineStages.find((stage) => stage.id === 'review')?.missions).toHaveLength(1);
    expect(board.archive).toHaveLength(1);
    expect(board.blockers).toHaveLength(1);
    expect(board.activeMission.acceptanceCriteria).toHaveLength(3);
    expect(board.agents.find((agent) => agent.id === 'mira').currentTask).toBe('Make change');
    expect(board.activeMission.thinking.rationale).toBe('Apply a policy-safe change and then review it.');
  });
});
