export const COMPANY_DEPARTMENTS = [
  {
    id: 'command',
    name: 'Command',
    description: 'Keeps the company goal aligned and visible.',
    accent: 'cyan',
  },
  {
    id: 'planning',
    name: 'Planning',
    description: 'Turns a goal into a mission plan and checkpoints.',
    accent: 'gold',
  },
  {
    id: 'production',
    name: 'Production',
    description: 'Builds the work order and keeps momentum moving.',
    accent: 'green',
  },
  {
    id: 'acceptance',
    name: 'Acceptance',
    description: 'Checks quality and decides whether the mission is ready.',
    accent: 'amber',
  },
  {
    id: 'operations',
    name: 'Operations',
    description: 'Protects the loop, handles retries, and watches health.',
    accent: 'violet',
  },
];

export const COMPANY_AGENTS = [
  {
    id: 'astra',
    name: 'Astra',
    title: 'Lead Operator',
    departmentId: 'command',
    avatar: 'AS',
    rank: 5,
    rankLabel: 'Chief',
    specialty: 'Owns the big goal and keeps every team aligned.',
    defaultFocus: 'Turn the workspace brief into a single mission.',
    accent: 'cyan',
  },
  {
    id: 'mira',
    name: 'Mira',
    title: 'Planning Director',
    departmentId: 'planning',
    avatar: 'MI',
    rank: 4,
    rankLabel: 'Director',
    specialty: 'Breaks a goal into clear subgoals and checkpoints.',
    defaultFocus: 'Translate the brief into a workable plan.',
    accent: 'gold',
  },
  {
    id: 'forge',
    name: 'Forge',
    title: 'Production Lead',
    departmentId: 'production',
    avatar: 'FO',
    rank: 4,
    rankLabel: 'Lead',
    specialty: 'Turns the mission into shipped work.',
    defaultFocus: 'Keep the build lane moving.',
    accent: 'green',
  },
  {
    id: 'quill',
    name: 'Quill',
    title: 'Acceptance Lead',
    departmentId: 'acceptance',
    avatar: 'QU',
    rank: 4,
    rankLabel: 'Lead',
    specialty: 'Verifies results and signs off releases.',
    defaultFocus: 'Check the result against acceptance criteria.',
    accent: 'amber',
  },
  {
    id: 'pulse',
    name: 'Pulse',
    title: 'Operations Manager',
    departmentId: 'operations',
    avatar: 'PU',
    rank: 3,
    rankLabel: 'Manager',
    specialty: 'Keeps the system healthy, recovers failures, and watches retries.',
    defaultFocus: 'Protect the loop from stalls and regressions.',
    accent: 'violet',
  },
];

export const DEFAULT_AGENT_ID = COMPANY_AGENTS[0].id;
export const DEFAULT_DEPARTMENT_ID = COMPANY_DEPARTMENTS[0].id;

export function getCompanyAgent(agentId) {
  return COMPANY_AGENTS.find((agent) => agent.id === agentId) ?? COMPANY_AGENTS[0];
}

export function getCompanyDepartment(departmentId) {
  return COMPANY_DEPARTMENTS.find((department) => department.id === departmentId) ?? COMPANY_DEPARTMENTS[0];
}

export function inferCompanyAssignment(task = {}, context = {}) {
  const sourceTask = context.sourceTask ?? null;
  const leadAgentId = context.leadAgentId ?? DEFAULT_AGENT_ID;
  const kind = String(task.kind ?? '').toLowerCase();
  const scope = String(task.scope ?? '').toLowerCase();

  if (task.ownerAgentId && task.departmentId) {
    return {
      ownerAgentId: task.ownerAgentId,
      departmentId: task.departmentId,
    };
  }

  if (sourceTask?.ownerAgentId || sourceTask?.departmentId) {
    return {
      ownerAgentId: sourceTask.ownerAgentId ?? leadAgentId,
      departmentId: sourceTask.departmentId ?? DEFAULT_DEPARTMENT_ID,
    };
  }

  if (scope === 'orchestrator') {
    return {
      ownerAgentId: DEFAULT_AGENT_ID,
      departmentId: 'command',
    };
  }

  if (kind.includes('review') || kind.includes('approve') || kind.includes('verify') || kind.includes('qa')) {
    return {
      ownerAgentId: 'quill',
      departmentId: 'acceptance',
    };
  }

  if (kind.includes('test') || kind.includes('check')) {
    return {
      ownerAgentId: 'quill',
      departmentId: 'acceptance',
    };
  }

  if (kind.includes('plan') || kind.includes('analysis')) {
    return {
      ownerAgentId: 'mira',
      departmentId: 'planning',
    };
  }

  if (kind.includes('maint') || kind.includes('ops') || kind.includes('health') || kind.includes('heartbeat')) {
    return {
      ownerAgentId: 'pulse',
      departmentId: 'operations',
    };
  }

  if (kind.includes('build') || kind.includes('execute') || kind.includes('write') || kind.includes('custom')) {
    return {
      ownerAgentId: 'forge',
      departmentId: 'production',
    };
  }

  if (task.autoGenerated) {
    return {
      ownerAgentId: leadAgentId,
      departmentId: 'command',
    };
  }

  return {
    ownerAgentId: leadAgentId,
    departmentId: 'production',
  };
}
